// command.c — see command.h. The table lists every command; lookup is by name (a linear scan,
// only done while parsing the config, never per key).

static const Command *const command_table[] = {
    &CMD_FORWARD_CHAR, &CMD_BACKWARD_CHAR, &CMD_NEXT_LINE, &CMD_PREVIOUS_LINE,
    &CMD_MOVE_BEGINNING_OF_LINE, &CMD_MOVE_END_OF_LINE, &CMD_FORWARD_WORD, &CMD_BACKWARD_WORD,
    &CMD_FORWARD_PARAGRAPH, &CMD_BACKWARD_PARAGRAPH, &CMD_BEGINNING_OF_BUFFER, &CMD_END_OF_BUFFER,
    &CMD_SCROLL_UP_COMMAND, &CMD_SCROLL_DOWN_COMMAND, &CMD_RECENTER_TOP_BOTTOM,
    &CMD_SELF_INSERT, &CMD_NEWLINE, &CMD_DELETE_BACKWARD_CHAR, &CMD_DELETE_CHAR, &CMD_SAVE_BUFFER,
    &CMD_KEYBOARD_QUIT, &CMD_SET_MARK_COMMAND, &CMD_EXCHANGE_POINT_AND_MARK, &CMD_MARK_WHOLE_BUFFER,
    &CMD_SAVE_BUFFERS_KILL_TERMINAL, &CMD_NEXT_BUFFER, &CMD_PREVIOUS_BUFFER,
    &CMD_OPEN_CONFIG, &CMD_RELOAD_CONFIG, &CMD_TEXT_SCALE_INCREASE, &CMD_TEXT_SCALE_DECREASE,
    &CMD_TEXT_SCALE_RESET, &CMD_DESCRIBE_KEY, &CMD_UNDO, &CMD_UNDO_REDO,
    &CMD_KILL_REGION, &CMD_KILL_RING_SAVE, &CMD_KILL_LINE, &CMD_KILL_WORD, &CMD_BACKWARD_KILL_WORD, &CMD_KILL_WHOLE_LINE,
    &CMD_YANK, &CMD_YANK_POP,
    &CMD_INDENT_FOR_TAB_COMMAND, &CMD_UNINDENT, &CMD_TAB_TO_TAB_STOP, &CMD_QUOTED_INSERT,
    &CMD_OPEN_LINE, &CMD_DELETE_INDENTATION, &CMD_DELETE_HORIZONTAL_SPACE, &CMD_JUST_ONE_SPACE, &CMD_TRANSPOSE_CHARS,
    &CMD_UPCASE_WORD, &CMD_DOWNCASE_WORD, &CMD_CAPITALIZE_WORD, &CMD_COMMENT_LINE,
    &CMD_EXIT_MINIBUFFER, &CMD_EXIT_MINIBUFFER_INPUT, &CMD_ABORT_MINIBUFFERS, &CMD_PREVIOUS_HISTORY_ELEMENT,
    &CMD_NEXT_HISTORY_ELEMENT, &CMD_MINIBUFFER_BACKWARD_UPDIR, &CMD_MINIBUFFER_COMPLETE, &CMD_MINIBUFFER_NEXT_COMPLETION,
    &CMD_MINIBUFFER_PREVIOUS_COMPLETION, &CMD_MINIBUFFER_NEXT_PAGE, &CMD_MINIBUFFER_PREVIOUS_PAGE, &CMD_EXECUTE_EXTENDED_COMMAND,
    &CMD_SWITCH_TO_BUFFER, &CMD_KILL_BUFFER, &CMD_FIND_FILE, &CMD_WRITE_FILE, &CMD_GOTO_LINE,
    &CMD_SAVE_SOME_BUFFERS, &CMD_REVERT_BUFFER, &CMD_SET_LANGUAGE,
    &CMD_ISEARCH_FORWARD, &CMD_ISEARCH_BACKWARD, &CMD_ISEARCH_REPEAT_FORWARD, &CMD_ISEARCH_REPEAT_BACKWARD, &CMD_ISEARCH_DELETE_CHAR,
    &CMD_ISEARCH_EXIT, &CMD_ISEARCH_ABORT, &CMD_ISEARCH_YANK_WORD, &CMD_ISEARCH_YANK_KILL, &CMD_ISEARCH_RING_RETREAT,
    &CMD_ISEARCH_RING_ADVANCE, &CMD_ISEARCH_TOGGLE_CASE_FOLD, &CMD_QUERY_REPLACE, &CMD_REPLACE_STRING,
};

const Command *command_find(String8 name) {
    for (i32 i = 0; i < ARRAY_COUNT(command_table); i++) {
        if (str8_equal(name, str8_cstr(command_table[i]->name))) return command_table[i];
    }
    return NULL;
}

i32 command_count(void) {
    return (i32)ARRAY_COUNT(command_table);
}

const Command *command_at(i32 index) {
    return index >= 0 && index < ARRAY_COUNT(command_table) ? command_table[index] : NULL;
}
