// config_default.h — the built-in configuration, embedded in the exe. The same format as the
// user's teal.conf and parsed by the same code at startup; open-config writes it out as the
// starting point of a new teal.conf. Keep it documenting every setting, color and the key notation.

static const char config_default[] =
    "# teal configuration\n"
    "#\n"
    "# teal reads this file at startup and again whenever it changes on disk. It has three\n"
    "# sections: [settings], [colors] and [keys]. Lines starting with '#' are comments (only at the\n"
    "# start of a line). A bad line is skipped and reported in the echo area and in *Messages*;\n"
    "# everything else still applies. Whatever this file leaves out keeps its built-in value, so a\n"
    "# short file with only your changes works too.\n"
    "#\n"
    "# Location: teal.conf next to teal.exe if that file exists (portable install), otherwise\n"
    "# %APPDATA%\\teal\\teal.conf. C-c , opens it (creating it from these defaults the first time)\n"
    "# and C-c r reloads it by hand.\n"
    "\n"
    "[settings]\n"
    "\n"
    "# Font family: a monospace font installed on the system. If it is missing, Consolas is used.\n"
    "font = Consolas\n"
    "\n"
    "# Font size in points, 4 to 96; decimals are allowed (10.5). The monitor's scale applies on top.\n"
    "# C-x C-+ and C-x C-- change it for the session only, C-x C-0 goes back to this value.\n"
    "font_size = 12\n"
    "\n"
    "# Line height in percent of the font's natural line height, 80 to 300.\n"
    "line_height = 100\n"
    "\n"
    "# Glyph rendering (ClearType): symmetric, natural or classic (GDI-like, crisper, narrower).\n"
    "render_mode = symmetric\n"
    "\n"
    "# Columns per tab stop, 1 to 16.\n"
    "tab_width = 4\n"
    "\n"
    "# Indentation: columns per level (1 to 16); with tabs or spaces; and whether a loaded file decides\n"
    "# tabs or spaces for its buffer from its first indented lines. RET indents the new line, TAB\n"
    "# reindents the line (or the region), a closing ) ] } typed first on a line reindents it. The rule:\n"
    "# the previous non-blank line's indentation, plus its brackets opened minus closed, minus the\n"
    "# closing brackets that start the line.\n"
    "indent_width = 4\n"
    "indent_with_tabs = false\n"
    "detect_indentation = true\n"
    "\n"
    "# true: '_' is part of a word for M-f / M-b. false: it separates words (Emacs' C mode).\n"
    "underscore_is_word = false\n"
    "\n"
    "# true: saving returns only once the file is on the disk (FlushFileBuffers). false: faster,\n"
    "# but a power failure right after saving can lose the file.\n"
    "fsync_on_save = true\n"
    "\n"
    "# Undo history kept per buffer, in megabytes (1 to 2048). The oldest changes are dropped first;\n"
    "# the last command can always be undone.\n"
    "undo_limit_mb = 64\n"
    "\n"
    "# true: the region (between point and mark) is highlighted while the mark is active, and region\n"
    "# commands act on it only then (Emacs' transient-mark-mode). Shift with a motion key selects.\n"
    "transient_mark_mode = true\n"
    "\n"
    "# true: typing (or yanking) with an active region replaces it. false (Emacs' default): typing\n"
    "# inserts at point; DEL and C-d still delete an active region.\n"
    "delete_selection_mode = false\n"
    "\n"
    "# Kills (C-w, C-k, M-d, ...) kept for yanking (C-y, then M-y for older ones), 1 to 1000. Every\n"
    "# kill also goes to the Windows clipboard, and C-y takes the clipboard when another program\n"
    "# changed it since.\n"
    "kill_ring_max = 60\n"
    "\n"
    "# Rows of the candidate list above the minibuffer (M-x, C-x C-f, C-x b ...), 1 to 40.\n"
    "completion_lines = 8\n"
    "\n"
    "# true: a buffer without unsaved changes whose file changed on disk is reloaded (when teal is\n"
    "# activated, and at once for the buffers on screen). A buffer with unsaved changes is never\n"
    "# touched, only flagged in the mode line. false: unchanged buffers are flagged too.\n"
    "auto_revert = true\n"
    "\n"
    "[colors]\n"
    "\n"
    "# Each color is #rrggbb. text is also the mode line (inverse video), punctuation and ordinary\n"
    "# identifiers. The syntax colors: comment, string, keyword, number, constant (true, null, Jai's\n"
    "# ---), type, variable (Jai declarations), function (definitions), directive (#include, #import,\n"
    "# @notes). The window caption follows background on Windows 11.\n"
    "background = #072626\n"
    "text       = #d3b58d\n"
    "cursor     = #90ee90\n"
    "selection  = #0000ff\n"
    "comment    = #3fdf1f\n"
    "string     = #0fdfaf\n"
    "keyword    = #ffffff\n"
    "number     = #7ad0c6\n"
    "type       = #8cde94\n"
    "variable   = #c1d1e3\n"
    "constant   = #7ad0c6\n"
    "function   = #ffffff\n"
    "directive  = #8cde94\n"
    "# The background of a bracket and its match while point is at one (show_paren_mode).\n"
    "paren_match = #4f94cd\n"
    "# The minibuffer: its prompt, the selected candidate's row, the matched part of each candidate.\n"
    "prompt               = #0fdfaf\n"
    "completion_selection = #0000ff\n"
    "completion_match     = #ffffff\n"
    "\n"
    "[keys]\n"
    "\n"
    "# One binding per line: a key sequence, then the command. The last word on the line is the\n"
    "# command and everything before it is the key sequence, so keys such as \"=\" need no quoting.\n"
    "# The command \"none\" removes a binding. Later lines win: binding a sequence removes the\n"
    "# bindings it conflicts with (binding C-x would remove every C-x ... binding), with a warning.\n"
    "#\n"
    "# Key notation, as Emacs' kbd:\n"
    "#   C- Ctrl, M- Alt (Meta), S- Shift, combined in any order: C-M-<home>.\n"
    "#   A character: a  5  /  {  ;  and so on. SPC is the space bar.\n"
    "#   Named keys: RET TAB ESC DEL (Backspace) <delete> <insert> <home> <end> <prior> (Page Up)\n"
    "#   <next> (Page Down) <left> <right> <up> <down> <f1> ... <f24> <pause> <apps>.\n"
    "#   A sequence is up to 4 keys separated by spaces: C-x C-s.\n"
    "#\n"
    "# Keys match by the character they type in the current keyboard layout: C-/ is Ctrl with\n"
    "# whatever key types \"/\". Shift is part of the character for everything except letters, so\n"
    "# Ctrl+Shift+/ on a US keyboard is C-? and letters keep it as a modifier: C-S-a. A key with\n"
    "# Shift and no binding runs the binding it has without Shift. Plain characters can be bound\n"
    "# too (they then stop inserting themselves); the second key of a sequence often is one (C-x o).\n"
    "# Because '#' starts a comment, a lone \"#\" key cannot be bound (M-# can).\n"
    "\n"
    "# Moving around\n"
    "C-f         forward-char\n"
    "C-b         backward-char\n"
    "C-n         next-line\n"
    "C-p         previous-line\n"
    "C-a         move-beginning-of-line\n"
    "C-e         move-end-of-line\n"
    "M-f         forward-word\n"
    "M-b         backward-word\n"
    "M-}         forward-paragraph\n"
    "M-{         backward-paragraph\n"
    "M-<         beginning-of-buffer\n"
    "M->         end-of-buffer\n"
    "<right>     forward-char\n"
    "<left>      backward-char\n"
    "<down>      next-line\n"
    "<up>        previous-line\n"
    "<home>      move-beginning-of-line\n"
    "<end>       move-end-of-line\n"
    "C-<right>   forward-word\n"
    "C-<left>    backward-word\n"
    "C-<down>    forward-paragraph\n"
    "C-<up>      backward-paragraph\n"
    "C-<home>    beginning-of-buffer\n"
    "C-<end>     end-of-buffer\n"
    "M-g g       goto-line\n"
    "M-g M-g     goto-line\n"
    "\n"
    "# Scrolling\n"
    "C-v         scroll-up-command\n"
    "M-v         scroll-down-command\n"
    "<next>      scroll-up-command\n"
    "<prior>     scroll-down-command\n"
    "C-l         recenter-top-bottom\n"
    "\n"
    "# Editing\n"
    "C-d         delete-char\n"
    "<delete>    delete-char\n"
    "DEL         delete-backward-char\n"
    "RET         newline\n"
    "C-m         newline\n"
    "C-j         newline\n"
    "TAB         indent-for-tab-command\n"
    "C-i         indent-for-tab-command\n"
    "<backtab>   unindent\n"
    "M-i         tab-to-tab-stop\n"
    "C-q         quoted-insert\n"
    "C-o         open-line\n"
    "M-^         delete-indentation\n"
    "M-\\         delete-horizontal-space\n"
    "M-SPC       just-one-space\n"
    "C-t         transpose-chars\n"
    "M-u         upcase-word\n"
    "M-l         downcase-word\n"
    "M-c         capitalize-word\n"
    "C-x C-;     comment-line\n"
    "M-;         comment-line\n"
    "\n"
    "# Mark and region\n"
    "C-SPC       set-mark-command\n"
    "C-@         set-mark-command\n"
    "C-x C-x     exchange-point-and-mark\n"
    "C-x h       mark-whole-buffer\n"
    "\n"
    "# Killing (cutting) and yanking (pasting)\n"
    "C-w           kill-region\n"
    "M-w           kill-ring-save\n"
    "C-k           kill-line\n"
    "M-d           kill-word\n"
    "M-DEL         backward-kill-word\n"
    "C-DEL         backward-kill-word\n"
    "C-<delete>    kill-word\n"
    "C-S-DEL       kill-whole-line\n"
    "C-y           yank\n"
    "M-y           yank-pop\n"
    "S-<insert>    yank\n"
    "C-<insert>    kill-ring-save\n"
    "S-<delete>    kill-region\n"
    "\n"
    "# Undo: C-/ undoes, and repeated it goes further back; after any other command it first\n"
    "# undoes the undos (Emacs). C-? (undo-redo) goes forward again.\n"
    "C-/         undo\n"
    "C-_         undo\n"
    "C-x u       undo\n"
    "C-?         undo-redo\n"
    "C-M-_       undo-redo\n"
    "\n"
    "# Files, buffers, quitting\n"
    "C-x C-f     find-file\n"
    "C-x C-s     save-buffer\n"
    "C-x C-w     write-file\n"
    "C-x s       save-some-buffers\n"
    "C-x C-c     save-buffers-kill-terminal\n"
    "C-x b       switch-to-buffer\n"
    "C-x k       kill-buffer\n"
    "C-x <left>  previous-buffer\n"
    "C-x <right> next-buffer\n"
    "M-x         execute-extended-command\n"
    "C-g         keyboard-quit\n"
    "ESC         keyboard-quit\n"
    "\n"
    "# Text size for this session\n"
    "C-x C-+     text-scale-increase\n"
    "C-x C-=     text-scale-increase\n"
    "C-x C--     text-scale-decrease\n"
    "C-x C-0     text-scale-reset\n"
    "\n"
    "# Help and this file\n"
    "C-h k       describe-key\n"
    "C-c ,       open-config\n"
    "C-c r       reload-config\n"
    "\n"
    "[keys minibuffer]\n"
    "\n"
    "# While the minibuffer reads something (M-x, C-x C-f, ...), these bindings come first; every other\n"
    "# key falls through to [keys] above, so all editing commands work in it. C-g and ESC abort any\n"
    "# prompt, including the y / n questions, whose other keys are taken as answers.\n"
    "# RET takes the selected candidate (or the input when there is no list), C-j the input exactly as\n"
    "# typed. TAB completes to the longest common part, then to the selection. Candidates match when\n"
    "# every space-separated word of the input occurs in them, ignoring case.\n"
    "RET         exit-minibuffer\n"
    "C-m         exit-minibuffer\n"
    "C-j         exit-minibuffer-input\n"
    "TAB         minibuffer-complete\n"
    "C-i         minibuffer-complete\n"
    "C-n         minibuffer-next-completion\n"
    "<down>      minibuffer-next-completion\n"
    "C-p         minibuffer-previous-completion\n"
    "<up>        minibuffer-previous-completion\n"
    "<next>      minibuffer-next-page\n"
    "<prior>     minibuffer-previous-page\n"
    "M-p         previous-history-element\n"
    "M-n         next-history-element\n"
    "DEL         minibuffer-backward-updir\n"
    "C-g         abort-minibuffers\n"
    "ESC         abort-minibuffers\n";
