// config_default.h — the built-in configuration, embedded in the exe. The same format as the
// user's teal.conf and parsed by the same code at startup; open-config writes it out as the
// starting point of a new teal.conf. Keep it documenting every setting, color and the key notation.

static const char config_default[] =
    "# teal configuration\n"
    "#\n"
    "# teal reads this file at startup and again whenever it changes on disk. It has three\n"
    "# sections: [settings], [colors] and [keys]. Lines starting with '#' are comments (only at the\n"
    "# start of a line). A bad line is skipped and reported in the echo area and in *Messages*;\n"
    "# everything else still applies. Whatever this file leaves out keeps its built-in value, so a\n"
    "# short file with only your changes works too.\n"
    "#\n"
    "# Location: teal.conf next to teal.exe if that file exists (portable install), otherwise\n"
    "# %APPDATA%\\teal\\teal.conf. C-c , opens it (creating it from these defaults the first time)\n"
    "# and C-c r reloads it by hand.\n"
    "\n"
    "[settings]\n"
    "\n"
    "# Font family: a monospace font installed on the system. If it is missing, Consolas is used.\n"
    "font = Consolas\n"
    "\n"
    "# Font size in points, 4 to 96; decimals are allowed (10.5). The monitor's scale applies on top.\n"
    "# C-x C-+ and C-x C-- change it for the session only, C-x C-0 goes back to this value.\n"
    "font_size = 12\n"
    "\n"
    "# Line height in percent of the font's natural line height, 80 to 300.\n"
    "line_height = 100\n"
    "\n"
    "# Glyph rendering (ClearType): symmetric, natural or classic (GDI-like, crisper, narrower).\n"
    "render_mode = symmetric\n"
    "\n"
    "# Columns per tab stop, 1 to 16.\n"
    "tab_width = 4\n"
    "\n"
    "# true: '_' is part of a word for M-f / M-b. false: it separates words (Emacs' C mode).\n"
    "underscore_is_word = false\n"
    "\n"
    "# true: saving returns only once the file is on the disk (FlushFileBuffers). false: faster,\n"
    "# but a power failure right after saving can lose the file.\n"
    "fsync_on_save = true\n"
    "\n"
    "# Undo history kept per buffer, in megabytes (1 to 2048). The oldest changes are dropped first;\n"
    "# the last command can always be undone.\n"
    "undo_limit_mb = 64\n"
    "\n"
    "[colors]\n"
    "\n"
    "# Each color is #rrggbb. text is also the mode line (inverse video). selection and the syntax\n"
    "# colors (comment ... variable) are used from the phases that bring regions and highlighting.\n"
    "# The window caption follows background on Windows 11.\n"
    "background = #072626\n"
    "text       = #d3b58d\n"
    "cursor     = #90ee90\n"
    "selection  = #0000ff\n"
    "comment    = #3fdf1f\n"
    "string     = #0fdfaf\n"
    "keyword    = #ffffff\n"
    "number     = #7ad0c6\n"
    "type       = #8cde94\n"
    "variable   = #c1d1e3\n"
    "\n"
    "[keys]\n"
    "\n"
    "# One binding per line: a key sequence, then the command. The last word on the line is the\n"
    "# command and everything before it is the key sequence, so keys such as \"=\" need no quoting.\n"
    "# The command \"none\" removes a binding. Later lines win: binding a sequence removes the\n"
    "# bindings it conflicts with (binding C-x would remove every C-x ... binding), with a warning.\n"
    "#\n"
    "# Key notation, as Emacs' kbd:\n"
    "#   C- Ctrl, M- Alt (Meta), S- Shift, combined in any order: C-M-<home>.\n"
    "#   A character: a  5  /  {  ;  and so on. SPC is the space bar.\n"
    "#   Named keys: RET TAB ESC DEL (Backspace) <delete> <insert> <home> <end> <prior> (Page Up)\n"
    "#   <next> (Page Down) <left> <right> <up> <down> <f1> ... <f24> <pause> <apps>.\n"
    "#   A sequence is up to 4 keys separated by spaces: C-x C-s.\n"
    "#\n"
    "# Keys match by the character they type in the current keyboard layout: C-/ is Ctrl with\n"
    "# whatever key types \"/\". Shift is part of the character for everything except letters, so\n"
    "# Ctrl+Shift+/ on a US keyboard is C-? and letters keep it as a modifier: C-S-a. A key with\n"
    "# Shift and no binding runs the binding it has without Shift. Plain characters can be bound\n"
    "# too (they then stop inserting themselves); the second key of a sequence often is one (C-x o).\n"
    "# Because '#' starts a comment, a lone \"#\" key cannot be bound (M-# can).\n"
    "\n"
    "# Moving around\n"
    "C-f         forward-char\n"
    "C-b         backward-char\n"
    "C-n         next-line\n"
    "C-p         previous-line\n"
    "C-a         move-beginning-of-line\n"
    "C-e         move-end-of-line\n"
    "M-f         forward-word\n"
    "M-b         backward-word\n"
    "M-}         forward-paragraph\n"
    "M-{         backward-paragraph\n"
    "M-<         beginning-of-buffer\n"
    "M->         end-of-buffer\n"
    "<right>     forward-char\n"
    "<left>      backward-char\n"
    "<down>      next-line\n"
    "<up>        previous-line\n"
    "<home>      move-beginning-of-line\n"
    "<end>       move-end-of-line\n"
    "C-<right>   forward-word\n"
    "C-<left>    backward-word\n"
    "C-<down>    forward-paragraph\n"
    "C-<up>      backward-paragraph\n"
    "C-<home>    beginning-of-buffer\n"
    "C-<end>     end-of-buffer\n"
    "\n"
    "# Scrolling\n"
    "C-v         scroll-up-command\n"
    "M-v         scroll-down-command\n"
    "<next>      scroll-up-command\n"
    "<prior>     scroll-down-command\n"
    "C-l         recenter-top-bottom\n"
    "\n"
    "# Editing (TAB inserts a tab character until indentation arrives)\n"
    "C-d         delete-char\n"
    "<delete>    delete-char\n"
    "DEL         delete-backward-char\n"
    "RET         newline\n"
    "C-m         newline\n"
    "C-j         newline\n"
    "TAB         self-insert-command\n"
    "\n"
    "# Undo: C-/ undoes, and repeated it goes further back; after any other command it first\n"
    "# undoes the undos (Emacs). C-? (undo-redo) goes forward again.\n"
    "C-/         undo\n"
    "C-_         undo\n"
    "C-x u       undo\n"
    "C-?         undo-redo\n"
    "C-M-_       undo-redo\n"
    "\n"
    "# Files, buffers, quitting\n"
    "C-x C-s     save-buffer\n"
    "C-x C-c     save-buffers-kill-terminal\n"
    "C-x <left>  previous-buffer\n"
    "C-x <right> next-buffer\n"
    "C-g         keyboard-quit\n"
    "ESC         keyboard-quit\n"
    "\n"
    "# Text size for this session\n"
    "C-x C-+     text-scale-increase\n"
    "C-x C-=     text-scale-increase\n"
    "C-x C--     text-scale-decrease\n"
    "C-x C-0     text-scale-reset\n"
    "\n"
    "# Help and this file\n"
    "C-h k       describe-key\n"
    "C-c ,       open-config\n"
    "C-c r       reload-config\n";
